export const theme = {
	'-font-size-paragraph': '14px',
	'-font-size-h1': '20px',
	'-font-size-h2': '18px',
	'--font-size-h3': '16px',
	'--background-color-primary': '#f2f2f2',
	'--background-color-secondary': '#e5e5e5',
	'--color-paragraph': '#8c8c8c',
	'--color-h1': '#be3323',
	'--color-h2': '#db4a39',
	'--color-h3': '#ec6a5b',
	'--color-link': '#4d4d4d',
	'--color-link-hover': '#c92a18',
	'--border-radius': '5px',
	'--color-box-shadow': '#bfbfbf66',
	'--background-button-primary': '#e51a24',
	'--background-button-primary-hover': '#cf1720',
	'--text-color-button-primary': '#f2f2f2',
	'--box-shadow-button-primary': '4px 4px 4px #b8141d80',
};
